services:
  monosi-server:
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile.api
    image: monosi/monosi-server:latest
  monosi-webapp:
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile.client
    image: monosi/monosi-webapp:latest
    environment:
      - REACT_APP_API_URL=http://0.0.0.0:3000/v1/api/
    ports:
      - "3000:80"
